version: '2'
 
services:
  santapostgres:
     image: santapostgres
     restart: always
     build:
       context: ./postgresdocker/
       dockerfile: Dockerfile
     ports:
       - 5432:5432
     environment:
         POSTGRES_PASSWORD: santa
#     volumes:
#       - pgdata:/var/lib/postgresql/data
 
#volumes:
#  pgdata: